export const props = [
  { nombre: 'color',
    default: 'primary',
    tipo: 'String',
    descripcion: 'Define el color de la Caja de Texto.' },
  { nombre: 'disabled',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Desactiva todos los controles del switch' },
  { nombre: 'items',
    default: '[]',
    tipo: 'Array',
    descripcion: 'Contiene la lista de controles que tendra el switch',
    important: true },
  { nombre: 'item_value',
    default: 'null',
    tipo: 'String',
    descripcion: 'Define la propiedad de el item que devolvera el switch, si se omite se devolvera el index',
    important: true },
  { nombre: 'label',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Controles con estilo Label' },
  { nombre: 'outline',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Controles con estilo Outline' },
  { nombre: 'return_object',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'define que el switch devuelva todo el objeto seleccionado' },
  { nombre: 'small',
    default: 'false',
    tipo: 'Boolean',
    descripcion: 'Controles con estilo Small' },
  { nombre: 'text_color',
    default: 'black',
    tipo: 'String',
    descripcion: 'Define el color de texto en generas, siempre y cuando no haya uno a nivel de item' },
  { nombre: 'unactive_color',
    default: 'grey lighten-1',
    tipo: 'String',
    descripcion: 'Define el color del control desactivado en generas, siempre y cuando no haya uno a nivel de item' }
]
